## Numpy Array Operation

In [1]:
import numpy as np

In [6]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,])
print("Basic slicing:",arr[3:9])
print("With step:",arr[3:9:2])
print("Negative Indexing:",arr[-4])

Basic slicing: [4 5 6 7 8 9]
With step: [4 6 8]
Negative Indexing: 7


In [14]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("specific element:",arr_2d[2, 2])
print("Entire row:",arr_2d[2])
print("Entire column:",arr_2d[:,2])

specific element: 9
Entire row: [7 8 9]
Entire column: [3 6 9]


### Sorting

In [19]:
unsorted=np.array([6,2,3,1,7,3,8,9])
print("Sorted array:",np.sort(unsorted))

arr_2d_unsorted=np.array([[6,3],[8,4],[5,9]])
print("Sorted 2d array:\n",np.sort(arr_2d_unsorted, axis=1))

Sorted array: [1 2 3 3 6 7 8 9]
Sorted 2d array:
 [[3 6]
 [4 8]
 [5 9]]


### Filter

In [21]:
num=np.array([1,2,3,4,5,6,7,8,9,10])
even_num=num[num%2==0]
print("Even:",even_num)
odd_num=num[num%2==1]
print("Odd:",odd_num)

Even: [ 2  4  6  8 10]
Odd: [1 3 5 7 9]


### Filter with mask

In [22]:
mask=num>5
print("Mask:",num[mask])

Mask: [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [26]:
indices=[0,3,9]
print(num[indices])

where_result=np.where(num>4)
print("Where:",num[where_result])

[ 1  4 10]
Where: [ 5  6  7  8  9 10]


In [32]:
conditional_array=np.where(num>7,num*2,num*3)
print("Condition:",conditional_array)

Condition: [ 3  6  9 12 15 18 21 16 18 20]


In [ ]:
if num>5:
    num*2
else:
    num*3

### Adding and removing data

In [37]:
arr1=np.array([1,2,3,])
arr2=np.array([4,5,6,])

combined=np.concatenate([arr1,arr2])
print("Combined ",combined)


Combined  [1 2 3 4 5 6]


### Array compatibility


In [39]:
a=np.array([1,2,3,])
b=np.array([4,5,])
c=np.array([6,7,])

print("Compatibility shape:",c.shape==b.shape)

Compatibility shape: True


In [42]:
original=np.array([[1,2,3],[4,5,6]])
new_row=np.array([7,8,9])

with_new_row=np.vstack([new_row,original])
print("Orig:",original)
print("with new row:",with_new_row)

new_col=np.array([[9],[10,]])
with_new_col=np.hstack([new_col,original])
print("New column:",with_new_col)

Orig: [[1 2 3]
 [4 5 6]]
with new row: [[7 8 9]
 [1 2 3]
 [4 5 6]]
New column: [[ 9  1  2  3]
 [10  4  5  6]]


In [43]:
arr=np.array([1,2,3,4,5,6,7,8,9,])
deleted=np.delete(arr,5)
print("Deleted:",deleted)

Deleted: [1 2 3 4 5 7 8 9]
