## Numpy Array and Basics
### learn about numpy with chai aur code

In [2]:
import numpy as np 

### creating array from list

In [9]:
arr_1d=np.array([1,2,3,4,])
print(arr_1d)

arr_2d=np.array([[1,2,3,],[4,5,6]])
print(arr_2d)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


### List vs numpy array


In [8]:
import time
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3])  # element wise multiplication
print("Python array multiplication ", np_array * 2)

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.1560077667236328

 Numpy operation time:  0.01037907600402832


### creating array from scratch