## Numpy Array and Basics
### learn about numpy with chai aur code

In [2]:
import numpy as np 

### creating array from list

In [9]:
arr_1d=np.array([1,2,3,4,])
print(arr_1d)

arr_2d=np.array([[1,2,3,],[4,5,6]])
print(arr_2d)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


### List vs numpy array


In [8]:
import time
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3])  # element wise multiplication
print("Python array multiplication ", np_array * 2)

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.1560077667236328

 Numpy operation time:  0.01037907600402832


### creating array from scratch

In [9]:
zeros= np.zeros((2,3))
print("zeros array :\n", zeros)

ones=np.ones((2,3))
print("ones array :\n", ones)

full =np.full((2,3), (2,))
print("full array :\n", full)

random=np.random.random((2,3))
print("random array :\n", random)

sequence=np.arange(1,10,3)
print("sequence array :\n", sequence)




zeros array :
 [[0. 0. 0.]
 [0. 0. 0.]]
ones array :
 [[1. 1. 1.]
 [1. 1. 1.]]
full array :
 [[2 2 2]
 [2 2 2]]
random array :
 [[0.79617936 0.99775092 0.49475709]
 [0.6820518  0.01560987 0.60620071]]
sequence array :
 [1 4 7]


### Vector ,Matrix & Tensor

In [10]:
vector=np.array([1,2,3])
print("Vector:", vector)

matrix=np.array([[1,2,3],
                 [4,5,6]])
print("Matrix:", matrix)

tensor=np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[0,0,0]]])
print("Tensor:", tensor)

Vector: [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]]
Tensor: [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 0 0]]]


### Array Properties

In [12]:
arr=np.array([[1,2,3],
              [4,5,6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64


### Array reshaping


In [21]:
arr=np.arange(12)
print("Original:",arr)

reshaped=arr.reshape((3,4))
print("Reshaped:\n",reshaped)

flattened=reshaped.flatten()
print("Flattened:\n",flattened)

#Returns view instead of copy 
raveled=reshaped.ravel()
print("Raveled :",raveled)

#!Transpose
transposed=reshaped.T
print("Transpose:\n",transposed)


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
